### ISSUE TITLE
[1.11.2] NoClassDefFoundError

### ISSUE THREAD

**Issue by Andronomos** [faceofcat/Tesla-Core-Lib#23]
I crash while loading the game after installing Industrial Foregoing 1.11.2-0.3-20 and Tesla Core Lib 1.11.2-0.7.3

> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tesla Core Lib (teslacorelib)
Caused by: java.lang.NoClassDefFoundError: net/darkhax/tesla/api/implementation/BaseTeslaContainer
	at net.ndrei.teslacorelib.TeslaCoreLib.preInit(TeslaCoreLib.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at 

Full crash log:  https://pastebin.com/Pyi5UTBa

**Comment by faceofcat** [comment]
did you also install Tesla?

**Comment by Andronomos** [comment]
@faceofcat I did not. I simply grabbed what was listed on the dependencies page but now that you mention it, it seems obvious.

**Comment by faceofcat** [comment]
for 1.10 and 1.11 Tesla is required.... for 1.12 it is not.

**Comment by Andronomos** [comment]
Ah, alright. My apologies for wasting your time. Thank you for your reply.
