### ISSUE TITLE
Crash: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method net.ndrei.teslacorelib.inventory.FluidStorage.fill, parameter resource

### ISSUE THREAD

**Issue by rezonant** [faceofcat/Tesla-Core-Lib#31]
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method net.ndrei.teslacorelib.inventory.FluidStorage.fill, parameter resource
        at net.ndrei.teslacorelib.inventory.FluidStorage.fill(FluidStorage.kt)
        at nc.tile.energyFluid.TileEnergyFluid.pushFluid(TileEnergyFluid.java:302)
        at nc.tile.energyFluid.TileBuffer.func_73660_a(TileBuffer.java:23)
        at net.minecraft.world.World.func_72939_s(World.java:1832)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:745)
```

Happened after I placed an XU transfer pipe connecting to a NuclearCraft buffer within a CompactMachine. I had a NC buffer on the bottom of the outside of the compact machine, another NC buffer next to a tunnel on the inside, power was flowing fine. I then accidentally connected the XU transfer pipe which was supplying water via a Fluid Transfer Node to the inside buffer and the server went belly up right away. Cross posting this on both Tesla and NC as I don't know who's at fault.

Complete crash report: https://pastebin.com/ajxjxjF9

**Comment by rezonant** [comment]
Issue filed at NuclearCraft: https://github.com/turbodiesel4598/NuclearCraft/issues/255

**Comment by faceofcat** [comment]
someone fed a null FluidStack into my machine...

that's something I should handle better... but still a weird thing to do :)

I will get it fixed on my side.
