### ISSUE TITLE
Dedicated server complete lockup - net.ndrei.teslacorelib.tileentities.SidedTileEntity.getAddon()78.22%

### ISSUE THREAD

**Issue by ProsperCraft** [faceofcat/Tesla-Core-Lib#40]
Here is a warmroast while it was locked up-
![teslacorewarmroast](https://user-images.githubusercontent.com/4427684/40327936-df7bb470-5d01-11e8-9ec5-a388c1ce8f91.png)

Here are the stall reports- 

[stall_reports.zip](https://github.com/MinecraftModDevelopmentMods/Tesla-Core-Lib/files/2023990/stall_reports.zip)

Here is an excerpt from the stall report - 

tall report from 2018-05-21 14:18:50 +0000, 193 threads, stalled for at least 1920000 ms.
Heap memory usage: 6585 / 11088 MB (max. 26642 MB).
Created by sampler 1.73 (MC 1.12).

"Server thread" #32 prio=5
RUNNABLE
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.getAddon(SidedTileEntity.kt:311)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.hasAddon(SidedTileEntity.kt:332)
	at com.buuz135.industrial.tile.agriculture.AnimalIndependenceSelectorTile.work(AnimalIndependenceSelectorTile.java:28)
	at com.buuz135.industrial.tile.WorkingAreaElectricMachine.performWork(WorkingAreaElectricMachine.java:91)
	at net.ndrei.teslacorelib.tileentities.ElectricMachine.protectedUpdate(ElectricMachine.kt:280)
	at com.buuz135.industrial.tile.CustomElectricMachine.protectedUpdate(CustomElectricMachine.java:98)
	at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:118)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt:988)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:247)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2864)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zll000(WorldServer.java:2851)
	at net.minecraft.world.World.func_72939_s(World.java:6623)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2219)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ProsperCraft** [comment]
It just happened again, here is another stall report.

https://gist.github.com/ProsperCraft/6c96dc991eeeb9a913fc259aea7c9279
