### ISSUE TITLE
Dangerous alternative prefix

### ISSUE THREAD

**Issue by TekuSP** [faceofcat/Tesla-Core-Lib#6]
```
[22:11:15] [Server thread/WARN] [FML]: ****************************************
[22:11:15] [Server thread/WARN] [FML]: * Dangerous alternative prefix `teslacorelib` for name `machine_case`, expected `industrialforegoing` invalid registry invocation/invalid name?
[22:11:15] [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:85)
[22:11:15] [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:95)
[22:11:15] [Server thread/WARN] [FML]: *  at net.ndrei.teslacorelib.items.RegisteredItem.<init>(RegisteredItem.kt:18)
[22:11:15] [Server thread/WARN] [FML]: *  at net.ndrei.teslacorelib.items.MachineCaseItem.<init>(MachineCaseItem.kt:10)
[22:11:15] [Server thread/WARN] [FML]: *  at net.ndrei.teslacorelib.items.MachineCaseItem.<clinit>(MachineCaseItem.kt:10)
[22:11:15] [Server thread/WARN] [FML]: *  at com.buuz135.industrial.tile.block.PetrifiedFuelGeneratorBlock.createRecipe(PetrifiedFuelGeneratorBlock.java:22)...
[22:11:15] [Server thread/WARN] [FML]: ****************************************
```
No crash, but should be solved.

Tesla 1.12-1.0.61
Tesla Core Lib 1.12-1.0.5
```
[21:50:07] [main/INFO] [FML]: Forge Mod Loader version 14.21.1.2420 for Minecraft 1.12 loading
[21:50:07] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_141, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_141
```

**Comment by faceofcat** [comment]
please submit that to the [Industrial Foregoing](https://github.com/Buuz135/Industrial-Foregoing) project... not really sure what @Buuz135 does there... :)

**Comment by Buuz135** [comment]
I just use `MachineCaseItem.INSTANCE`, I don't know where the issue is

**Comment by faceofcat** [comment]
when are you using it?...

could it be that you use it before register items event?... that would be quite bad.

**Comment by Buuz135** [comment]
On pre but I use `dependencies = "required-after:teslacorelib"`

**Comment by faceofcat** [comment]
yes... but in 1.12 you don't register items/recipes on preInit... :)

you have specialized events for that.

```kotlin
    @SubscribeEvent
    fun registerBlocks(ev: RegistryEvent.Register<Block>) {
    }

    @SubscribeEvent
    fun registerItems(ev: RegistryEvent.Register<Item>) {
    }

    @SubscribeEvent
    fun registerRecipes(ev: RegistryEvent.Register<IRecipe>) {
    }

```

**Comment by TekuSP** [comment]
@Buuz135 so Industrial Foregoing will be updated to fix that, right?

**Comment by faceofcat** [comment]
it kind of has to... because I just did an evil thing and added a check to see if any of the items are used before being registered... and crashing the game if they are... :)... sorry @Buuz135
